CREATE SEQUENCE  TM_LZ.SEQ_ETL_ID  as bigint NO MINVALUE no MAXVALUE INCREMENT BY 1 START WITH 1;

CREATE TABLE TM_LZ.LT_SRC_CLINICAL_DATA
   (	STUDY_ID VARCHAR(25), 
	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	VISIT_NAME VARCHAR(100), 
	DATA_LABEL VARCHAR(500), 
	DATA_VALUE VARCHAR(500), 
	CATEGORY_CD VARCHAR(250), 
	DATA_LABEL_CTRL_VOCAB_CODE VARCHAR(200), 
	DATA_VALUE_CTRL_VOCAB_CODE VARCHAR(500), 
	DATA_LABEL_COMPONENTS VARCHAR(1000), 
	UNITS_CD VARCHAR(50), 
	VISIT_DATE VARCHAR(50), 
	LINK_TYPE VARCHAR(20), 
	LINK_VALUE VARCHAR(200), 
	END_DATE VARCHAR(50), 
	VISIT_REFERENCE VARCHAR(100), 
	DATE_IND CHAR(1), 
	OBS_STRING VARCHAR(100), 
	VALUETYPE_CD VARCHAR(50)
   );

CREATE TABLE TM_LZ.LT_SRC_DEAPP_ANNOT 
   (	GPL_ID VARCHAR(100), 
	PROBE_ID VARCHAR(100), 
	GENE_SYMBOL VARCHAR(100), 
	GENE_ID VARCHAR(250), 
	ORGANISM VARCHAR(200)
   );

CREATE TABLE TM_LZ.LT_SRC_MRNA_DATA 
   (	TRIAL_NAME VARCHAR(25), 
	PROBESET VARCHAR(100), 
	EXPR_ID VARCHAR(100), 
	INTENSITY_VALUE VARCHAR(50)
   );

CREATE TABLE TM_LZ.LT_SRC_MRNA_SUBJ_SAMP_MAP 
   (	TRIAL_NAME VARCHAR(100), 
	SITE_ID VARCHAR(100), 
	SUBJECT_ID VARCHAR(100), 
	SAMPLE_CD VARCHAR(100), 
	PLATFORM VARCHAR(100), 
	TISSUE_TYPE VARCHAR(100), 
	ATTRIBUTE_1 VARCHAR(256), 
	ATTRIBUTE_2 VARCHAR(200), 
	CATEGORY_CD VARCHAR(200), 
	SOURCE_CD VARCHAR(200)
   );

CREATE TABLE TM_LZ.LT_SRC_SEARCH_KEYWORD 
   (	KEYWORD VARCHAR(300), 
	DISPLAY_CATEGORY VARCHAR(300), 
	DATA_CATEGORY VARCHAR(200), 
	SOURCE_CD VARCHAR(200), 
	UID_PREFIX VARCHAR(20), 
	UNIQUE_ID VARCHAR(300), 
	PARENT_TERM VARCHAR(300)
   );

CREATE TABLE TM_LZ.LT_SRC_STUDY_METADATA 
   (	STUDY_ID VARCHAR(100), 
	TITLE VARCHAR(1000), 
	DESCRIPTION VARCHAR(4000), 
	DESIGN VARCHAR(2000), 
	START_DATE VARCHAR(50), 
	COMPLETION_DATE VARCHAR(50), 
	PRIMARY_INVESTIGATOR VARCHAR(400), 
	CONTACT_FIELD VARCHAR(400), 
	STATUS VARCHAR(100), 
	OVERALL_DESIGN VARCHAR(2000), 
	INSTITUTION VARCHAR(100), 
	COUNTRY VARCHAR(50), 
	BIOMARKER_TYPE VARCHAR(255), 
	TARGET VARCHAR(255), 
	ACCESS_TYPE VARCHAR(100), 
	STUDY_OWNER VARCHAR(510), 
	STUDY_PHASE VARCHAR(100), 
	BLINDING_PROCEDURE VARCHAR(1000), 
	STUDYTYPE VARCHAR(510), 
	DURATION_OF_STUDY_WEEKS VARCHAR(200), 
	NUMBER_OF_PATIENTS VARCHAR(200), 
	NUMBER_OF_SITES VARCHAR(200), 
	ROUTE_OF_ADMINISTRATION VARCHAR(510), 
	DOSING_REGIMEN VARCHAR(3500), 
	GROUP_ASSIGNMENT VARCHAR(510), 
	TYPE_OF_CONTROL VARCHAR(510), 
	PRIMARY_END_POINTS VARCHAR(2000), 
	SECONDARY_END_POINTS VARCHAR(3500), 
	INCLUSION_CRITERIA VARCHAR(4000), 
	EXCLUSION_CRITERIA VARCHAR(4000), 
	SUBJECTS VARCHAR(2000), 
	GENDER_RESTRICTION_MFB VARCHAR(510), 
	MIN_AGE VARCHAR(100), 
	MAX_AGE VARCHAR(100), 
	SECONDARY_IDS VARCHAR(510), 
	DEVELOPMENT_PARTNER VARCHAR(100), 
	GEO_PLATFORM VARCHAR(100), 
	MAIN_FINDINGS VARCHAR(2000), 
	SEARCH_AREA VARCHAR(100), 
	COMPOUND VARCHAR(1000), 
	DISEASE VARCHAR(1000), 
	PUBMED_IDS VARCHAR(4000), 
	ORGANISM VARCHAR(200)
   );

CREATE TABLE TM_LZ.LT_SRC_STUDY_METADATA_AD_HOC 
   (	STUDY_ID VARCHAR(100), 
	AD_HOC_PROPERTY_KEY VARCHAR(500), 
	AD_HOC_PROPERTY_VALUE VARCHAR(4000), 
	AD_HOC_PROPERTY_LINK VARCHAR(500)
   );

CREATE TABLE TM_LZ.LT_SRC_SUBJ_ENROLL_DATE 
   (	STUDY_ID VARCHAR(25), 
	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	ENROLL_DATE VARCHAR(25)
   );

CREATE TABLE TM_LZ.LZ_SRC_ANALYSIS_METADATA 
   (	STUDY_ID VARCHAR(50), 
	DATA_TYPE VARCHAR(50), 
	ANALYSIS_NAME VARCHAR(500), 
	DESCRIPTION VARCHAR(500), 
	PHENOTYPE_IDS VARCHAR(250), 
	POPULATION VARCHAR(500), 
	TISSUE VARCHAR(500), 
	GENOME_VERSION VARCHAR(50), 
	GENOTYPE_PLATFORM_IDS VARCHAR(500), 
	EXPRESSION_PLATFORM_IDS VARCHAR(500), 
	STATISTICAL_TEST VARCHAR(500), 
	RESEARCH_UNIT VARCHAR(500), 
	SAMPLE_SIZE VARCHAR(500), 
	CELL_TYPE VARCHAR(500), 
	PVALUE_CUTOFF VARCHAR(50), 
	ETL_DATE TIMESTAMP, 
	FILENAME VARCHAR(500), 
	STATUS VARCHAR(50), 
	PROCESS_DATE TIMESTAMP, 
	ETL_ID NUMERIC(38,0), 
	ANALYSIS_NAME_ARCHIVED VARCHAR(500), 
	MODEL_NAME VARCHAR(500), 
	MODEL_DESC VARCHAR(500), 
	SENSITIVE_FLAG NUMERIC(18,0), 
	SENSITIVE_DESC VARCHAR(500)
   );

CREATE TABLE TM_LZ.LZ_SRC_CLINICAL_DATA 
   (	STUDY_ID VARCHAR(25), 
	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	VISIT_NAME VARCHAR(100), 
	DATA_LABEL VARCHAR(500), 
	DATA_VALUE VARCHAR(500), 
	CATEGORY_CD VARCHAR(250), 
	ETL_JOB_ID NUMERIC(22,0), 
	ETL_DATE TIMESTAMP, 
	DATA_LABEL_CTRL_VOCAB_CODE VARCHAR(200), 
	DATA_VALUE_CTRL_VOCAB_CODE VARCHAR(500), 
	DATA_LABEL_COMPONENTS VARCHAR(1000), 
	UNITS_CD VARCHAR(50), 
	VISIT_DATE VARCHAR(50), 
	LINK_TYPE VARCHAR(20), 
	LINK_VALUE VARCHAR(200), 
	END_DATE VARCHAR(50), 
	VISIT_REFERENCE VARCHAR(100), 
	DATE_IND CHAR(1), 
	OBS_STRING VARCHAR(100), 
	VALUETYPE_CD VARCHAR(50)
   );

CREATE TABLE TM_LZ.LZ_SRC_MRNA_DATA 
   (	TRIAL_NAME VARCHAR(25), 
	PROBESET VARCHAR(100), 
	EXPR_ID VARCHAR(100), 
	INTENSITY_VALUE VARCHAR(50), 
	SOURCE_CD VARCHAR(200)
   );

CREATE TABLE TM_LZ.LZ_SRC_MRNA_SUBJ_SAMP_MAP 
   (	TRIAL_NAME VARCHAR(100), 
	SITE_ID VARCHAR(100), 
	SUBJECT_ID VARCHAR(100), 
	SAMPLE_CD VARCHAR(100), 
	PLATFORM VARCHAR(100), 
	TISSUE_TYPE VARCHAR(100), 
	ATTRIBUTE_1 VARCHAR(256), 
	ATTRIBUTE_2 VARCHAR(200), 
	CATEGORY_CD VARCHAR(200), 
	SOURCE_CD VARCHAR(50)
   );

CREATE TABLE TM_LZ.LZ_SRC_STUDY_METADATA 
   (	STUDY_ID VARCHAR(100), 
	TITLE VARCHAR(1000), 
	DESCRIPTION VARCHAR(4000), 
	DESIGN VARCHAR(2000), 
	START_DATE VARCHAR(50), 
	COMPLETION_DATE VARCHAR(50), 
	PRIMARY_INVESTIGATOR VARCHAR(400), 
	CONTACT_FIELD VARCHAR(400), 
	STATUS VARCHAR(100), 
	OVERALL_DESIGN VARCHAR(2000), 
	INSTITUTION VARCHAR(100), 
	COUNTRY VARCHAR(50), 
	BIOMARKER_TYPE VARCHAR(255), 
	TARGET VARCHAR(255), 
	ACCESS_TYPE VARCHAR(100), 
	STUDY_OWNER VARCHAR(510), 
	STUDY_PHASE VARCHAR(100), 
	BLINDING_PROCEDURE VARCHAR(1000), 
	STUDYTYPE VARCHAR(510), 
	DURATION_OF_STUDY_WEEKS VARCHAR(200), 
	NUMBER_OF_PATIENTS VARCHAR(200), 
	NUMBER_OF_SITES VARCHAR(200), 
	ROUTE_OF_ADMINISTRATION VARCHAR(510), 
	DOSING_REGIMEN VARCHAR(3500), 
	GROUP_ASSIGNMENT VARCHAR(510), 
	TYPE_OF_CONTROL VARCHAR(510), 
	PRIMARY_END_POINTS VARCHAR(2000), 
	SECONDARY_END_POINTS VARCHAR(3500), 
	INCLUSION_CRITERIA VARCHAR(4000), 
	EXCLUSION_CRITERIA VARCHAR(4000), 
	SUBJECTS VARCHAR(2000), 
	GENDER_RESTRICTION_MFB VARCHAR(510), 
	MIN_AGE VARCHAR(100), 
	MAX_AGE VARCHAR(100), 
	SECONDARY_IDS VARCHAR(510), 
	DEVELOPMENT_PARTNER VARCHAR(100), 
	GEO_PLATFORM VARCHAR(100), 
	MAIN_FINDINGS VARCHAR(2000), 
	SEARCH_AREA VARCHAR(100), 
	COMPOUND VARCHAR(1000), 
	DISEASE VARCHAR(1000), 
	PUBMED_IDS VARCHAR(4000), 
	ORGANISM VARCHAR(200), 
	UPLOAD_DATE TIMESTAMP
   );

CREATE TABLE TM_LZ.LZ_SRC_STUDY_METADATA_AD_HOC 
   (	STUDY_ID VARCHAR(100), 
	AD_HOC_PROPERTY_KEY VARCHAR(500), 
	AD_HOC_PROPERTY_VALUE VARCHAR(4000), 
	AD_HOC_PROPERTY_LINK VARCHAR(500), 
	UPLOAD_DATE TIMESTAMP
   );

CREATE TABLE TM_LZ.LZ_SRC_SUBJ_ENROLL_DATE 
   (	STUDY_ID VARCHAR(25), 
	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	ENROLL_DATE VARCHAR(25)
   );

CREATE TABLE TM_LZ.RWG_ANALYSIS_DATA 
   (	STUDY_ID VARCHAR(200), 
	PROBESET VARCHAR(200), 
	FOLD_CHANGE NUMERIC(18,5), 
	PVALUE NUMERIC(18,5), 
	RAW_PVALUE NUMERIC(18,5), 
	MIN_LSMEAN NUMERIC(18,5), 
	MAX_LSMEAN NUMERIC(18,5), 
	ANALYSIS_CD VARCHAR(100), 
	BIO_ASSAY_ANALYSIS_ID NUMERIC(18,0), 
	ADJUSTED_PVALUE NUMERIC(18,5)
   );

