
CREATE TABLE TM_WZ.WRK_CLINICAL_DATA 
   (	STUDY_ID VARCHAR(25), 
	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	VISIT_NAME VARCHAR(100), 
	DATA_LABEL VARCHAR(500), 
	DATA_VALUE VARCHAR(500), 
	CATEGORY_CD VARCHAR(250), 
	ETL_JOB_ID NUMERIC(22,0), 
	ETL_DATE TIMESTAMP, 
	USUBJID VARCHAR(200), 
	CATEGORY_PATH VARCHAR(1000), 
	DATA_TYPE VARCHAR(10), 
	DATA_LABEL_CTRL_VOCAB_CODE VARCHAR(200), 
	DATA_VALUE_CTRL_VOCAB_CODE VARCHAR(500), 
	DATA_LABEL_COMPONENTS VARCHAR(1000), 
	UNITS_CD VARCHAR(50), 
	VISIT_DATE VARCHAR(50), 
	LEAF_NODE VARCHAR(700), 
	NODE_NAME VARCHAR(1000), 
	LINK_TYPE VARCHAR(20), 
	LINK_VALUE VARCHAR(200), 
	END_DATE VARCHAR(50), 
	VISIT_REFERENCE VARCHAR(100), 
	DATE_IND CHAR(1), 
	OBS_STRING VARCHAR(100), 
	REC_NUM NUMERIC(18,0), 
	VALUETYPE_CD VARCHAR(50)
   );

CREATE TABLE TM_WZ.WRK_MRNA_DATA 
   (	PROBESET VARCHAR(100), 
	EXPR_ID VARCHAR(100), 
	RAW_INTENSITY VARCHAR(50)
   );

CREATE TABLE TM_WZ.WT_CLINICAL_DATA_DUPS 
   (	SITE_ID VARCHAR(50), 
	SUBJECT_ID VARCHAR(20), 
	VISIT_NAME VARCHAR(100), 
	DATA_LABEL VARCHAR(500), 
	CATEGORY_CD VARCHAR(250), 
	LINK_VALUE VARCHAR(500)
   );

CREATE TABLE TM_WZ.WT_CLINICAL_ENCOUNTER 
   (	LINK_TYPE VARCHAR(20), 
	LINK_VALUE VARCHAR(500), 
	ENCOUNTER_NUM NUMERIC
   );

CREATE TABLE TM_WZ.WT_DEL_NODES 
   (	C_FULLNAME VARCHAR(1000), 
	C_BASECODE VARCHAR(500)
   );

CREATE TABLE TM_WZ.WT_FOLDER_NODES 
   (	FOLDER_PATH VARCHAR(700), 
	FOLDER_NAME VARCHAR(2000)
   );

CREATE TABLE TM_WZ.WT_MIXED_TYPES 
   (	CATEGORY_CD VARCHAR(250), 
	DATA_LABEL VARCHAR(500), 
	VISIT_NAME VARCHAR(100)
   );

CREATE TABLE TM_WZ.WT_MRNA_DATA 
   (	PROBESET VARCHAR(100), 
	EXPR_ID VARCHAR(100), 
	INTENSITY_VALUE VARCHAR(50)
   );

CREATE TABLE TM_WZ.WT_MRNA_NODES 
   (	LEAF_NODE VARCHAR(2000), 
	CATEGORY_CD VARCHAR(2000), 
	PLATFORM VARCHAR(2000), 
	TISSUE_TYPE VARCHAR(2000), 
	ATTRIBUTE_1 VARCHAR(2000), 
	ATTRIBUTE_2 VARCHAR(2000), 
	TITLE VARCHAR(2000), 
	NODE_NAME VARCHAR(2000), 
	CONCEPT_CD VARCHAR(100), 
	TRANSFORM_METHOD VARCHAR(2000), 
	NODE_TYPE VARCHAR(50)
   );

CREATE TABLE TM_WZ.WT_MRNA_NODE_VALUES 
   (	CATEGORY_CD VARCHAR(2000), 
	PLATFORM VARCHAR(2000), 
	TISSUE_TYPE VARCHAR(2000), 
	ATTRIBUTE_1 VARCHAR(2000), 
	ATTRIBUTE_2 VARCHAR(2000), 
	TITLE VARCHAR(2000), 
	TRANSFORM_METHOD VARCHAR(2000)
   );

CREATE TABLE TM_WZ.WT_MRNA_SUBJ_SAMPLE_MAP 
   (	TRIAL_NAME VARCHAR(100), 
	SITE_ID VARCHAR(100), 
	SUBJECT_ID VARCHAR(100), 
	SAMPLE_CD VARCHAR(100), 
	PLATFORM VARCHAR(100), 
	TISSUE_TYPE VARCHAR(100), 
	ATTRIBUTE_1 VARCHAR(256), 
	ATTRIBUTE_2 VARCHAR(200), 
	CATEGORY_CD VARCHAR(200)
   );

CREATE TABLE TM_WZ.WT_NUM_DATA_TYPES 
   (	CATEGORY_CD VARCHAR(200), 
	DATA_LABEL VARCHAR(500), 
	SAMPLE_TYPE VARCHAR(100), 
	VISIT_NAME VARCHAR(100)
   );

CREATE TABLE TM_WZ.WT_SUBJECT_INFO 
   (	USUBJID VARCHAR(100), 
	AGE_IN_YEARS_NUM NUMERIC(3,0), 
	SEX_CD VARCHAR(50), 
	RACE_CD VARCHAR(50)
   );

CREATE TABLE TM_WZ.WT_SUBJECT_MICROARRAY_CALCS 
   (	TRIAL_NAME VARCHAR(50), 
	PROBESET_ID NUMERIC(22,0), 
	MEAN_INTENSITY NUMERIC, 
	MEDIAN_INTENSITY NUMERIC, 
	STDDEV_INTENSITY NUMERIC
   );

CREATE TABLE TM_WZ.WT_SUBJECT_MICROARRAY_LOGS 
   (	PROBESET_ID NUMERIC(22,0), 
	INTENSITY_VALUE NUMERIC, 
	PVALUE FLOAT8, 
	NUM_CALLS NUMERIC, 
	ASSAY_ID NUMERIC(18,0), 
	PATIENT_ID NUMERIC(18,0), 
	SAMPLE_ID NUMERIC(18,0), 
	SUBJECT_ID VARCHAR(50), 
	TRIAL_NAME VARCHAR(50), 
	TIMEPOINT VARCHAR(100), 
	LOG_INTENSITY NUMERIC
   );

CREATE TABLE TM_WZ.WT_SUBJECT_MICROARRAY_MED 
   (	PROBESET_ID NUMERIC(22,0), 
	INTENSITY_VALUE NUMERIC, 
	LOG_INTENSITY NUMERIC, 
	ASSAY_ID NUMERIC(18,0), 
	PATIENT_ID NUMERIC(18,0), 
	SAMPLE_ID NUMERIC(18,0), 
	SUBJECT_ID VARCHAR(50), 
	TRIAL_NAME VARCHAR(50), 
	TIMEPOINT VARCHAR(100), 
	PVALUE FLOAT8, 
	NUM_CALLS NUMERIC, 
	MEAN_INTENSITY NUMERIC, 
	STDDEV_INTENSITY NUMERIC, 
	MEDIAN_INTENSITY NUMERIC, 
	ZSCORE NUMERIC
   );

CREATE TABLE TM_WZ.WT_SUBJECT_MRNA_DATA 
   (	PROBESET VARCHAR(500), 
	EXPR_ID VARCHAR(500), 
	INTENSITY_VALUE NUMERIC, 
	ASSAY_ID NUMERIC(18,0), 
	PATIENT_ID NUMERIC(22,0), 
	SAMPLE_ID NUMERIC(18,0), 
	SUBJECT_ID VARCHAR(100), 
	TRIAL_NAME VARCHAR(200), 
	TIMEPOINT VARCHAR(200), 
	SAMPLE_TYPE VARCHAR(200), 
	PLATFORM VARCHAR(200), 
	TISSUE_TYPE VARCHAR(200)
   );

CREATE TABLE TM_WZ.WT_SUBJECT_MRNA_PROBESET 
   (	PROBESET_ID NUMERIC(38,0), 
	EXPR_ID VARCHAR(500), 
	INTENSITY_VALUE NUMERIC, 
	NUM_CALLS NUMERIC, 
	PVALUE NUMERIC, 
	ASSAY_ID NUMERIC(18,0), 
	PATIENT_ID NUMERIC(22,0), 
	SAMPLE_ID NUMERIC(18,0), 
	SUBJECT_ID VARCHAR(100), 
	TRIAL_NAME VARCHAR(200), 
	TIMEPOINT VARCHAR(200), 
	SAMPLE_TYPE VARCHAR(200), 
	PLATFORM VARCHAR(200), 
	TISSUE_TYPE VARCHAR(200)
   );

CREATE TABLE TM_WZ.WT_TRIAL_NODES 
   (	LEAF_NODE VARCHAR(4000), 
	CATEGORY_CD VARCHAR(200), 
	VISIT_NAME VARCHAR(100), 
	SAMPLE_TYPE VARCHAR(100), 
	DATA_LABEL VARCHAR(500), 
	NODE_NAME VARCHAR(500), 
	DATA_VALUE VARCHAR(500), 
	DATA_TYPE VARCHAR(20), 
	DATA_LABEL_CTRL_VOCAB_CODE VARCHAR(500), 
	DATA_VALUE_CTRL_VOCAB_CODE VARCHAR(500), 
	DATA_LABEL_COMPONENTS VARCHAR(1000), 
	LINK_TYPE VARCHAR(50), 
	OBS_STRING VARCHAR(100), 
	VALUETYPE_CD VARCHAR(50), 
	REC_NUM NUMERIC
   );

CREATE TABLE TM_WZ.WT_VOCAB_NODES 
   (	LEAF_NODE VARCHAR(1000), 
	MODIFIER_CD VARCHAR(100), 
	LABEL_NODE VARCHAR(1000), 
	VALUE_INSTANCE NUMERIC(18,0), 
	LABEL_INSTANCE NUMERIC(18,0)
   );
