CREATE OR REPLACE PROCEDURE TM_CZ.CZX_END_AUDIT(BIGINT, CHARACTER VARYING(100))
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	P_JOB_ID ALIAS FOR $1;
	P_JOB_STATUS ALIAS FOR $2;
	--ENDDATE TIMESTAMP;
BEGIN

--ENDDATE := now();

	UPDATE TM_CZ.CZ_JOB_MASTER
		SET 
			ACTIVE='N',
			END_DATE = current_timestamp,--ENDDATE,
      TIME_ELAPSED_SECS = 123456, /*
      EXTRACT (DAY    FROM (ENDDATE - START_DATE))*24*60*60 + 
      EXTRACT (HOUR   FROM (ENDDATE - START_DATE))*60*60 + 
      EXTRACT (MINUTE FROM (ENDDATE - START_DATE))*60 + 
      EXTRACT (SECOND FROM (ENDDATE - START_DATE))*/
			JOB_STATUS = P_JOB_STATUS
		WHERE ACTIVE='Y' 
		AND JOB_ID = P_JOB_ID;

RETURN 0;

exception 
when OTHERS then
	RAISE NOTICE 'Exception Raised: %', SQLERRM;

END;
END_PROC;

