CREATE OR REPLACE PROCEDURE TM_CZ.CZX_WRITE_AUDIT(BIGINT, CHARACTER VARYING(ANY), CHARACTER VARYING(ANY), CHARACTER VARYING(ANY), NUMERIC(ANY), NUMERIC(ANY), CHARACTER VARYING(ANY))
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	JOBID ALIAS FOR $1;
	DATABASENAME ALIAS FOR $2;
	PROCEDURENAME ALIAS FOR $3;
	STEPDESC ALIAS FOR $4;
	RECORDSMANIPULATED ALIAS FOR $5;
	STEPNUMBER ALIAS FOR $6;
	STEPSTATUS ALIAS FOR $7;
	
	LASTTIME	TIMESTAMP;
  	v_version_id numeric;
	startTime	timestamp;
	
BEGIN

  select now() into startTime;
  SELECT MAX(JOB_DATE)
    INTO LASTTIME
    FROM TM_CZ.CZ_JOB_AUDIT
    WHERE JOB_ID = JOBID;

	INSERT 	INTO TM_CZ.CZ_JOB_AUDIT(
		SEQ_ID,
		JOB_ID,
		DATABASE_NAME,
 		PROCEDURE_NAME,
 		STEP_DESC,
		RECORDS_MANIPULATED,
		STEP_NUMBER,
		STEP_STATUS,
    JOB_DATE,
    TIME_ELAPSED_SECS
	)
	SELECT
	    next value for tm_cz.SEQ_CZ_JOB_AUDIT,
 		JOBID,
		DATABASENAME,
		PROCEDURENAME,
		STEPDESC,
		RECORDSMANIPULATED,
		STEPNUMBER,
		STEPSTATUS,
    	startTime,
   --   10000; 
	  COALESCE(
      EXTRACT (DAY    FROM (startTime - LASTTIME))*24*60*60 +
      EXTRACT (HOUR   FROM (startTime - LASTTIME))*60*60 +
      EXTRACT (MINUTE FROM (startTime - LASTTIME))*60 +
      EXTRACT (SECOND FROM (startTime - LASTTIME))
      ,0);

RETURN 0;
exception 
when OTHERS then
	RAISE NOTICE 'Exception Raised: %', SQLERRM;
	return -16;
END;

END_PROC;