CREATE OR REPLACE PROCEDURE TM_CZ.CZX_WRITE_INFO(BIGINT, INTEGER, INTEGER, CHARACTER VARYING(ANY), CHARACTER VARYING(ANY))
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	JOBID ALIAS FOR $1;
	MESSAGEID ALIAS FOR $2;
	MESSAGELINE ALIAS FOR $3;
	MESSAGEPROC ALIAS FOR $4;
	INFOMESSAGE ALIAS FOR $5;
BEGIN

   INSERT INTO TM_CZ.CZ_JOB_MESSAGE
     ( JOB_ID, MESSAGE_ID, MESSAGE_LINE, MESSAGE_PROCEDURE, INFO_MESSAGE )
     VALUES ( JOBID, MESSAGEID, MESSAGELINE, MESSAGEPROC, INFOMESSAGE );

RETURN 0;

exception 
when OTHERS then
	RAISE NOTICE 'Exception Raised: %', SQLERRM;
END;

END_PROC;

