CREATE OR REPLACE PROCEDURE TM_CZ.CZX_END_AUDIT(BIGINT, CHARACTER VARYING(100))
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	P_JOB_ID ALIAS FOR $1;
	P_JOB_STATUS ALIAS FOR $2;
	v_end_date TIMESTAMP;
BEGIN

	select now() into v_end_date;

	UPDATE TM_CZ.CZ_JOB_MASTER
		SET 
			ACTIVE='N',
			END_DATE = v_end_date,
      TIME_ELAPSED_SECS = COALESCE(
      EXTRACT (DAY    FROM (START_DATE - v_end_date))*24*60*60 +
      EXTRACT (HOUR   FROM (START_DATE - v_end_date))*60*60 +
      EXTRACT (MINUTE FROM (START_DATE - v_end_date))*60 +
      EXTRACT (SECOND FROM (START_DATE - v_end_date))
      ,0),
			JOB_STATUS = P_JOB_STATUS
		WHERE ACTIVE='Y' 
		AND JOB_ID = P_JOB_ID;

RETURN 0;

exception 
when OTHERS then
	RAISE NOTICE 'Exception Raised: %', SQLERRM;

END;
END_PROC;

