--------------------------------------------------------
--  DDL for Table BIO_AD_HOC_PROPERTY
--------------------------------------------------------

  CREATE TABLE "BIOMART"."BIO_AD_HOC_PROPERTY" 
   (	"AD_HOC_PROPERTY_ID" NUMBER(22,0), 
	"BIO_DATA_ID" NUMBER(22,0), 
	"PROPERTY_KEY" NVARCHAR2(50), 
	"PROPERTY_VALUE" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART" ;
--------------------------------------------------------
--  DDL for Index BIO_AD_HOC_PROPERTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIOMART"."BIO_AD_HOC_PROPERTY_PK" ON "BIOMART"."BIO_AD_HOC_PROPERTY" ("AD_HOC_PROPERTY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX" ;
--------------------------------------------------------
--  Constraints for Table BIO_AD_HOC_PROPERTY
--------------------------------------------------------

  ALTER TABLE "BIOMART"."BIO_AD_HOC_PROPERTY" MODIFY ("AD_HOC_PROPERTY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRG_BIO_AD_HOC_PROP_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_AD_HOC_PROP_ID" before
  INSERT ON "BIOMART"."BIO_AD_HOC_PROPERTY" FOR EACH row BEGIN IF inserting THEN IF :NEW."AD_HOC_PROPERTY_ID" IS NULL THEN
  SELECT SEQ_BIO_DATA_ID.nextval INTO :NEW."AD_HOC_PROPERTY_ID" FROM dual;
END IF;
END IF;
END;
/
ALTER TRIGGER "BIOMART"."TRG_BIO_AD_HOC_PROP_ID" ENABLE;
